version: '3'

services:
  app:
    container_name: ams-app
    image: ghcr.io/zetroot/safehouseams.back:staging
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
    - /var/log/safehouse-ams/:/logs/
    - /var/lib/safehouse-ams/letucce-accounts/:/app/accounts/
    - /var/lib/safehouse-ams/ssl-certs/:/certs/

  postgres:
    container_name: ams-pgsql
    image: postgres:13
    restart: always
    volumes:
      - /var/lib/safehouse-ams/db-data/:/var/lib/postgresql/data/
    env_file:
      - .env.postgres
