domains:
  - domain: crm.dev-maca.ca
    type: PRIMARY
    zone: dev-maca.ca
name: safehouse-ams
region: blr
static_sites:
  - catchall_document: index.html
    dockerfile_path: Dockerfile.wasm
    github:
      branch: master
      repo: zetroot/SafeHouseAMS
    index_document: index.html
    name: safehouse-ams-wasm
    output_dir: /app/wwwroot
    routes:
      - path: /
