name: smoke test
on:
  push:
    branches: [ master ]

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  smoke:
    uses: zetroot/SafehouseAMS/.github/workflows/build_job.yml@master
    with:
      send_testcoverage: true
