name: smoke test
on:
  push:
    branches: [ master ]

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
    - name: get sources
      uses: actions/checkout@v2

    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.0.x

    - name: restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    # тестирование со сборкой результатов покрытия по конфигурации в файле по умолчанию
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat code coverage" --settings coverlet.runsettings

    # публикация результатов покрытия тестами на code-cov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0

  smoke_2:
    uses: zetroot/SafehouseAMS/.github/workflows/build_job.yml@master
    with:
      send_testcoverage: true
